version: '2.3'
services:
    data_collector0:
        build: ../../
        volumes:
            - ../../:/app
            - ../../../jass-train-py/data/conv_observation_full_0.75_quantile:/data
        network_mode: host
        command: >
            bash -c "cd scripts && python collect_n_send_game_data.py
            --host http://10.180.39.13
            --max_parallel_processes 16
            --max_parallel_threads 2
            --min_states_to_send 1"

