version: '2.3'
services:
    data_collector0:
        build: ../../
        volumes:
            - ../../:/app
        environment:
            - NVIDIA_VISIBLE_DEVICES=0
        network_mode: host
        command: >
            bash -c "cd scripts && python collect_n_send_game_data.py
            --host http://10.180.39.13
            --max_parallel_processes 7
            --min_states_to_send 1"



    data_collector1:
        build: ../../
        volumes:
            - ../../:/app
        environment:
            - NVIDIA_VISIBLE_DEVICES=1
        network_mode: host
        command: >
            bash -c "cd scripts && python collect_n_send_game_data.py
            --host http://10.180.39.13
            --max_parallel_processes 7
            --min_states_to_send 1"
