version: '3.8'
services:
    data_collector0:
        build: ../
        volumes:
            - ../:/app
        network_mode: host
        command: >
            bash -c "cd scripts && python collect_n_send_game_data.py
            --host http://10.180.39.13
            --port 8080
            --new_games_per_step 640
            --max_parallel_processes 64
            --max_parallel_threads 10
            --n_buffer_executors 16
            --model_execution_buffer_timeout 0.001
            --min_model_buffer_size 8
            --visible_gpu_index 0"
        deploy:
          resources:
            reservations:
              devices:
                - driver: nvidia
                  device_ids: ['0']
                  capabilities: [gpu]


    data_collector1:
        build: ../
        volumes:
            - ../:/app
        network_mode: host
        command: >
            bash -c "cd scripts && python collect_n_send_game_data.py
            --host http://10.180.39.13
            --port 8080
            --new_games_per_step 640
            --max_parallel_processes 64
            --max_parallel_threads 10
            --n_buffer_executors 16
            --model_execution_buffer_timeout 0.001
            --min_model_buffer_size 8
            --visible_gpu_index 1"
        deploy:
          resources:
            reservations:
              devices:
                - driver: nvidia
                  device_ids: ['1']
                  capabilities: [gpu]